version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: deploy/setup.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: deploy/deploy.sh
      timeout: 60
      runas: {brand}
  ApplicationStart:
    - location: deploy/upgrade.sh
      timeout: 60
      runas: {brand}
