version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: setup.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: {brand}
  ApplicationStart:
    - location: upgrade.sh
      timeout: 60
      runas: {brand}
